// This file is auto-generated by `poyo generate` — DO NOT EDIT.
// Regenerated on `poyo generate` and by every `poyo route` command.
// No hand edits survive.

import type { RouteEntry } from "@rubichandrap/poyo/runtime";

export const routeManifest =
[
  {
    "path": "/",
    "name": "Home",
    "files": {
      "react": "src/pages/Home/index.page.tsx",
      "view": "Views/Home/Index.cshtml"
    },
    "access": "guest",
    "seo": {
      "description": "A minimal React + .NET 10 MPA starter framework",
      "title": "Poyo Framework"
    }
  },
  {
    "path": "/Dashboard",
    "name": "Dashboard",
    "files": {
      "react": "src/pages/Dashboard/index.page.tsx",
      "view": "Views/Dashboard/Index.cshtml"
    },
    "access": "protected",
    "seo": {
      "description": "Protected dashboard area",
      "title": "Dashboard"
    }
  },
  {
    "path": "/Login",
    "name": "Login",
    "files": {
      "react": "src/pages/Login/index.page.tsx",
      "view": "Views/Login/Index.cshtml"
    },
    "access": "guest",
    "seo": {
      "description": "Sign in to Poyo framework demo",
      "title": "Login"
    }
  },
  {
    "path": "/Register",
    "name": "Register",
    "files": {
      "react": "src/pages/Register/index.page.tsx",
      "view": "Views/Register/Index.cshtml"
    },
    "access": "guest",
    "seo": {
      "description": "Page for Register",
      "title": "Register"
    }
  }
] as const satisfies readonly RouteEntry[];

export type RouteName = "Home" | "Dashboard" | "Login" | "Register";
export type RoutePath = "/" | "/Dashboard" | "/Login" | "/Register";

const routePaths: Record<RouteName, RoutePath> = {
	"Home": "/",
	"Dashboard": "/Dashboard",
	"Login": "/Login",
	"Register": "/Register",
};

export function routePath(name: RouteName): RoutePath {
	return routePaths[name];
}
