import fs from "node:fs";
import path from "node:path";
import { Command } from "commander";
import { getPaths } from "../config.js";
import { CliError } from "../error.js";

interface ViteManifestChunk {
	file: string;
	isEntry?: boolean;
	css?: string[];
	assets?: string[];
}

export function buildCommand(): Command {
	return new Command("build")
		.description(
			"Sync the client bundle into the server's wwwroot from the Vite manifest",
		)
		.action(() => {
			const paths = getPaths();
			syncClientAssets(paths.clientDir, paths.serverDir);
		});
}

export function syncClientAssets(clientDir: string, serverDir: string): void {
	const viteManifestPath = path.join(
		clientDir,
		"dist",
		".vite",
		"manifest.json",
	);
	if (!fs.existsSync(viteManifestPath)) {
		throw new CliError(`Vite manifest not found at: ${viteManifestPath}`);
	}

	const viteManifest = JSON.parse(
		fs.readFileSync(viteManifestPath, "utf-8"),
	) as Record<string, ViteManifestChunk>;

	const entryKey = Object.keys(viteManifest).find(
		(key) => viteManifest[key].isEntry,
	);
	if (!entryKey) {
		throw new CliError("Could not find entry point in Vite manifest");
	}

	const entryChunk = viteManifest[entryKey];
	const mainJs = entryChunk.file;
	const mainCss = entryChunk.css?.[0] ?? null;

	const activeFiles = new Set<string>();
	for (const key in viteManifest) {
		const chunk = viteManifest[key];
		activeFiles.add(chunk.file);
		for (const cssFile of chunk.css ?? []) {
			activeFiles.add(cssFile);
		}
		for (const assetFile of chunk.assets ?? []) {
			activeFiles.add(assetFile);
		}
	}

	const generatedAssetsPath = path.join(serverDir, "wwwroot", "generated");
	if (!fs.existsSync(generatedAssetsPath)) {
		fs.mkdirSync(generatedAssetsPath, { recursive: true });
	} else {
		const existingFiles = fs.readdirSync(generatedAssetsPath);
		for (const file of existingFiles) {
			const relativePath = `generated/${file}`;
			if (activeFiles.has(relativePath)) continue;
			const stalePath = path.join(generatedAssetsPath, file);
			if (fs.statSync(stalePath).isDirectory()) continue;
			try {
				fs.unlinkSync(stalePath);
			} catch {
				// Locked file (e.g. open on Windows); skip rather than abort the build.
			}
		}
	}

	const distPath = path.join(clientDir, "dist");
	for (const file of activeFiles) {
		const srcPath = path.join(distPath, file);
		const destPath = path.join(serverDir, "wwwroot", file);
		fs.mkdirSync(path.dirname(destPath), { recursive: true });
		if (fs.existsSync(srcPath)) {
			fs.copyFileSync(srcPath, destPath);
		}
	}

	const rootRelative = (file: string) =>
		file.startsWith("/") ? file : `/${file}`;
	const entryAssets = {
		js: rootRelative(mainJs),
		css: mainCss ? rootRelative(mainCss) : null,
	};

	const manifestPath = path.join(serverDir, "wwwroot", "manifest.json");
	fs.writeFileSync(manifestPath, JSON.stringify(entryAssets, null, 2));

	writeReactAssets(serverDir, entryAssets);
}

function writeReactAssets(
	serverDir: string,
	assets: { js: string; css: string | null },
): void {
	const scriptsPath = path.join(
		serverDir,
		"Views",
		"Shared",
		"_ReactAssets.cshtml",
	);
	fs.mkdirSync(path.dirname(scriptsPath), { recursive: true });
	const scriptsContent = `@*
    This file is automatically generated - DO NOT EDIT
    Generated by React build process
*@

<script type="module" crossorigin src="${assets.js}"></script>
${
	assets.css ? `<link rel="stylesheet" crossorigin href="${assets.css}">` : ""
}`;
	fs.writeFileSync(scriptsPath, scriptsContent);
}
