import fs from "node:fs";
import path from "node:path";
import type { ProjectPaths } from "./config.js";
import { readRoutes } from "./registry.js";

const HEADER = `// This file is auto-generated by \`poyo generate\` — DO NOT EDIT.
// Regenerated on \`poyo generate\` and by every \`poyo route\` command.
// No hand edits survive. Imported by no one.

import type {} from "@rubichandrap/poyo/runtime";
`;

/**
 * Emits the ambient route manifest (`<client>/routes.generated.ts`)
 * at the client package root (ADR 0010): an ambient module augmentation
 * of `@rubichandrap/poyo/runtime`'s `PoyoRouteRegistry` interface with
 * `names` and `paths` literal unions.
 *
 * The generated file is imported by no one and gitignored; routes.json stays
 * the only edited source of truth.
 */
export function writeRouteManifest(paths: ProjectPaths): void {
	const routes = readRoutes(paths);
	fs.mkdirSync(paths.clientDir, { recursive: true });
	const nameLiterals = routes.map((route) => JSON.stringify(route.name));
	const pathLiterals = routes.map((route) => JSON.stringify(route.path));
	// An empty registry must still produce valid TS: `never` unions make the
	// literal types unusable (correct — there are no routes) instead of
	// emitting a syntax error.
	const namesUnion =
		nameLiterals.length > 0 ? nameLiterals.join(" | ") : "never";
	const pathsUnion =
		pathLiterals.length > 0 ? pathLiterals.join(" | ") : "never";

	const content = [
		HEADER,
		'declare module "@rubichandrap/poyo/runtime" {',
		"\tinterface PoyoRouteRegistry {",
		`\t\tnames: ${namesUnion};`,
		`\t\tpaths: ${pathsUnion};`,
		"\t}",
		"}",
		"",
	].join("\n");

	fs.writeFileSync(path.join(paths.clientDir, "routes.generated.ts"), content);
}
