import fs from "node:fs";
import path from "node:path";
import type { ProjectPaths } from "./config.js";
import { readRoutes } from "./registry.js";

const HEADER = `// This file is auto-generated by \`poyo generate\` — DO NOT EDIT.
// Source of truth: routes.json (commit that file, not this one).
// Regenerated on \`poyo generate\` (predev/prebuild) and by every
// \`poyo route\` command — no hand edits survive.

import type { RouteEntry } from "@rubichandrap/poyo/runtime";
`;

/**
 * Emits the typed route table (`<client>/src/routes/routes.generated.ts`)
 * next to the route adapter (ADR 0006): the registry as literal types
 * (`as const satisfies readonly RouteEntry[]`) plus `RouteName`/`RoutePath`
 * unions and a `routePath(name)` helper, so static code cannot drift from
 * routes.json. The generated file is gitignored; routes.json stays the only
 * edited source of truth.
 */
export function writeRouteManifest(paths: ProjectPaths): void {
	const routes = readRoutes(paths);
	const routesDir = path.join(paths.clientDir, "src", "routes");
	fs.mkdirSync(routesDir, { recursive: true });

	const manifestJson = JSON.stringify(routes, null, 2);
	const nameLiterals = routes.map((route) => JSON.stringify(route.name));
	const pathLiterals = routes.map((route) => JSON.stringify(route.path));
	// An empty registry must still produce valid TS: `never` unions make the
	// literal types unusable (correct — there are no routes) instead of
	// emitting a syntax error.
	const namesUnion =
		nameLiterals.length > 0 ? nameLiterals.join(" | ") : "never";
	const pathsUnion =
		pathLiterals.length > 0 ? pathLiterals.join(" | ") : "never";

	const content = [
		HEADER,
		"export const routeManifest =",
		`${manifestJson} as const satisfies readonly RouteEntry[];`,
		"",
		`export type RouteName = ${namesUnion};`,
		`export type RoutePath = ${pathsUnion};`,
		"",
		"const routePaths: Record<RouteName, RoutePath> = {",
		...routes.map(
			(route) =>
				`\t${JSON.stringify(route.name)}: ${JSON.stringify(route.path)},`,
		),
		"};",
		"",
		"export function routePath(name: RouteName): RoutePath {",
		"\treturn routePaths[name];",
		"}",
		"",
	].join("\n");

	fs.writeFileSync(path.join(routesDir, "routes.generated.ts"), content);
}
