/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/Auth/Login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["LoginRequest"];
					"text/json": components["schemas"]["LoginRequest"];
					"application/*+json": components["schemas"]["LoginRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JSendResponseOfLoginResponse"];
						"application/json": components["schemas"]["JSendResponseOfLoginResponse"];
						"text/json": components["schemas"]["JSendResponseOfLoginResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JSendResponseOfObject"];
						"application/json": components["schemas"]["JSendResponseOfObject"];
						"text/json": components["schemas"]["JSendResponseOfObject"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/Auth/Refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["RefreshRequest"];
					"text/json": components["schemas"]["RefreshRequest"];
					"application/*+json": components["schemas"]["RefreshRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JSendResponseOfLoginResponse"];
						"application/json": components["schemas"]["JSendResponseOfLoginResponse"];
						"text/json": components["schemas"]["JSendResponseOfLoginResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JSendResponseOfObject"];
						"application/json": components["schemas"]["JSendResponseOfObject"];
						"text/json": components["schemas"]["JSendResponseOfObject"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/Auth/Logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["JSendResponseOfLogoutResponse"];
						"application/json": components["schemas"]["JSendResponseOfLogoutResponse"];
						"text/json": components["schemas"]["JSendResponseOfLogoutResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		JSendResponseOfLoginResponse: {
			status?: string;
			data?: unknown | components["schemas"]["LoginResponse"];
			message?: string | null;
		};
		JSendResponseOfLogoutResponse: {
			status?: string;
			data?: unknown | components["schemas"]["LogoutResponse"];
			message?: string | null;
		};
		JSendResponseOfObject: {
			status?: string;
			data?: unknown;
			message?: string | null;
		};
		LoginRequest: {
			username: string;
			password: string;
			rememberMe?: boolean;
			appType?: string;
		};
		LoginResponse: {
			token?: string;
			refreshToken?: string;
			/** Format: date-time */
			expiration?: string;
			username?: string;
		};
		LogoutResponse: {
			message?: string;
			success?: boolean;
		};
		RefreshRequest: {
			token?: string;
			refreshToken?: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
